import { slugify } from 'transliteration';

// แมปปิ้งความเร็วของเอฟเฟกต์ภาพในภาษาไทย/ทั่วไปให้เป็นตัวเลขวินาทีตามมาตรฐาน Ren'Py
const RENPY_SPEED_MAP = {
  none: 0.0,
  fast: 0.2,
  normal: 0.5,
  slow: 1.5,
};

export function escapeDialog(text) {
    if (text === null || text === undefined || typeof text === "object") return "";
    
    return String(text)
        .replace(/\\/g, '\\\\') // 1. ต้องแปลง \ เป็น \\ ก่อนเพื่อนเพื่อไม่ให้รวน
        .replace(/"/g, '\\"')   // 2. แปลง " เป็น \" เพื่อครอบ String ใน Ren'Py
        .replace(/\[/g, '[[');  // 3. ป้องกัน Ren'Py แครชจากเครื่องหมาย [ เดี่ยวๆ
}

export const isInvalidValue = (val) => {
    // เช็คเฉพาะตัวแปรที่ไม่มีค่าจริงๆ ป้องกันเลข 0 หรือ false หลุดมาติดบั๊ก
    if (val === null || val === undefined) return true;
    
    const str = String(val).trim();
    if (str === "") return true;

    // เช็คว่าเป็นคำเริ่มต้นเป๊ะๆ หรือเริ่มต้นด้วยคำนี้ตามด้วยตัวเลข (เช่น บล็อกใหม่ 1, New Block 2)
    // โดยใส่ flag 'i' เพื่อให้ไม่สนใจอักษรพิมพ์เล็ก-พิมพ์ใหญ่ (Case-insensitive)
    const defaultPattern = /^(บล็อกใหม่|New Block)(\s+\d+)?$/i;
    
    return defaultPattern.test(str);
};

// ใช้ค้นหาอ็อบเจกต์ Asset จากใน Array ด้วยเงื่อนไขสารพัดประโยชน์ (หาด้วย ID, ชื่อ หรือชื่อไฟล์ก็ได้)
export const findAsset = (value, assets) => {
  if (!value) return null;
  const strVal = String(value).trim();
  return assets?.find(
    (a) => String(a.id) === strVal || String(a.name) === strVal || String(a.file_name) === strVal
  ) || null;
};

// ฟังก์ชันล้างข้อความให้เหลือเฉพาะอักขระที่ Ren'Py นำไปใช้ตั้งชื่อตัวแปรได้ (อังกฤษ, ตัวเลข, Underscore)
export const cleanForScriptToken = (text, fallbackPrefix = "asset", assetId = "") => {
  if (!text) return assetId ? `${fallbackPrefix}_${String(assetId).substring(0, 8)}` : fallbackPrefix;
  let textStr = String(text).trim();

  // หากเป็นภาษาไทย ให้กรองอักษรไทยออก หรือยุบเป็นพิมพ์เล็กเพื่อความปลอดภัยของตัวแปร
  if (/[\u0e00-\u0e7f]/.test(textStr)) {
    let engOnly = textStr.replace(/[^a-zA-Z0-9_\s]/g, "").trim().replace(/\s+/g, " ");
    if (engOnly) return engOnly.toLowerCase();
    return assetId ? `${fallbackPrefix}_${String(assetId).substring(0, 8)}` : fallbackPrefix; 
  }

  const res = textStr.toLowerCase().replace(/[^a-z0-9_\s]/g, "").replace(/\s+/g, " ");
  return res || (assetId ? `${fallbackPrefix}_${String(assetId).substring(0, 8)}` : fallbackPrefix);
};

// เจเนอเรตชื่อของ Asset ที่จะปรากฏในสคริปต์สอดคล้องกับแท็กตัวละครและท่าทาง
export const generateScriptAssetName = (asset, fallbackValue) => {
  if (!asset) return cleanForScriptToken(fallbackValue);

  if (asset.main_tag) {
    const mainTagClean = cleanForScriptToken(asset.main_tag, "tag", asset.id);
    if (!mainTagClean.startsWith("tag_") || !asset.file_name) {
      const rawExpression = asset.expression_tag || asset.expression;
      if (rawExpression) {
        const cleanExpr = cleanForScriptToken(asset.expression, "expr", asset.id);
        return `${mainTagClean} ${cleanExpr}`;
      }
      return mainTagClean;
    }
  }

  const nameWithoutExt = asset.file_name ? asset.file_name.replace(/\.[^.]+$/, "") : (asset.name || "asset");
  return cleanForScriptToken(nameWithoutExt, "asset", asset.id);
};

// เจเนอเรตชื่อไฟล์ดิบปลายทางที่จะนำไปหย่อนลง ZIP (รักษาไฟล์ประเภท .png หรือ .mp3 ไว้)
export const generateZipFileName = (asset, isAudio) => {
  const matchExt = asset.file_name ? asset.file_name.match(/\.[^.]+$/) : null;
  const ext = matchExt ? matchExt[0].toLowerCase() : (isAudio ? ".mp3" : ".png");

  if (asset.main_tag) {
    const mainTagClean = cleanForScriptToken(asset.main_tag, "tag", asset.id);
    if (!mainTagClean.startsWith("tag_") || !asset.file_name) {
      if (asset.expression) {
        const cleanExpr = cleanForScriptToken(asset.expression, "expr", asset.id);
        return `${mainTagClean} ${cleanExpr}${ext}`; 
      }
      return `${mainTagClean}${ext}`;
    }
  }

  const nameWithoutExt = asset.file_name ? asset.file_name.replace(/\.[^.]+$/, "") : (asset.name || "asset");
  return cleanForScriptToken(nameWithoutExt, "asset", asset.id) + ext;
};

// 🎯 ฟังก์ชั่นหลักในการแปลง Data เป็นสคริปต์สคริปต์เขียนไฟล์ .rpy
// -------------------------------------------------------------
// 📌 จุดที่ 2: ฟังก์ชันหลัก `compileRenPyScript` (ตัวคอมไพล์เนื้อเรื่องหลัก)
// -------------------------------------------------------------
// ทำหน้าที่ร้อยเรียงฉาก ตัวละคร บทสนทนา และตรรกะทั้งหมดออกมาเป็นชุดคำสั่งข้อความของ `script.rpy`
export function compileRenPyScript(projectName, chapters, blocks, assets) {
  let rpyContent = `# ⚠️ Generated by Ren'Py Scenario Management System\n`;
  rpyContent += `# Project: ${projectName}\n\n`;

  // นิยามพิกัดและแกนวางภาพสไปรต์ครึ่งตัว (Half-Body Position Overrides) ให้ภาพตั้งบนขอบจออย่างสมดุล
  rpyContent += `# ==========================================\n`;
rpyContent += `# AUTO GENERATED: HALF-BODY CONFIGURATION OVERRIDE\n`;
rpyContent += `# ==========================================\n`;

rpyContent += `transform left:
    xalign 0.16
    yalign 1.0

transform center:
    xalign 0.50
    yalign 1.0

transform right:
    xalign 0.84
    yalign 1.0
# ==========================================\n\n`;

  const allCharacterNames = new Set();
  const charMap = {};

  // วนลูปเก็บรายชื่อตัวละครทั้งหมดในโปรเจกต์ เพื่อเตรียมเขียนประกาศตัวแปรล่วงหน้า (Character Definitions)
  if (chapters?.[0]?.start_characters) {
    try {
      const parsedConfigChars = typeof chapters[0].start_characters === "string" 
        ? JSON.parse(chapters[0].start_characters) 
        : chapters[0].start_characters;
      if (Array.isArray(parsedConfigChars)) {
        parsedConfigChars.forEach((item) => {
          const nameStr = typeof item === "string" ? item : item.name || item.value;
          if (nameStr && nameStr.trim() !== "") allCharacterNames.add(nameStr.trim());
        });
      }
    } catch (e) {
      console.error("ไม่สามารถแกะข้อมูล start_characters:", e);
    }
  }

  blocks?.forEach((block) => {
    if (block.character_name && block.character_name.trim() !== "") {
      allCharacterNames.add(block.character_name.trim());
    }
  });

  // เขียนประกาศตัวแปรยัดลงหัวไฟล์สคริปต์ เช่น `define ch_hero = Character("ผู้กล้า")`
  if (allCharacterNames.size > 0) {
    rpyContent += `# ==========================================\n# CHARACTER DEFINITIONS\n# ==========================================\n`;
    let charCounter = 1;
    allCharacterNames.forEach((name) => {
      let cleanName = name.toLowerCase().replace(/[^a-z0-9_]/g, "_").replace(/_+/g, "_");
      if (!cleanName || /[\u0e00-\u0e7f]/.test(name)) cleanName = `char_${charCounter++}`;
      const varName = `ch_${cleanName}`;
      charMap[name] = varName;
      rpyContent += `define ${varName} = Character("${escapeDialog(name)}", color="#000000")\n`;
    });
    rpyContent += `\n`;
  }

  // แปลงเนื้อหาทีละตอน (Chapter Loops) โดย Chapter แรกสุดจะถูกบังคับแปลงชื่อฉลากเป็น `label start:` เสมอตามกฎ Ren'Py
  chapters?.forEach((chapter, index) => {
    let labelName = chapter.label_name || `chapter_${String(chapter.id).replace(/-/g, "_")}`;
    if (index === 0) labelName = "start";

    rpyContent += `label ${labelName}:\n`;

    // เซ็ตอัปฉากเริ่มต้นและเพลงประกอบตอนเริ่มเกมใน Chapter แรกสุด
    
      if (chapter.start_bg_asset_id || chapter.start_bg_name) {
        const initialBg = chapter.start_bg_name || chapter.start_bg_asset_id;
        const asset = findAsset(initialBg, assets);
        rpyContent += `    scene ${generateScriptAssetName(asset, initialBg || "bg_placeholder")} with dissolve\n`;
      }
      if (chapter.start_music_asset_id || chapter.start_music_name) {
        const initialMusic = chapter.start_music_name || chapter.start_music_asset_id;
        const asset = findAsset(initialMusic, assets);
        rpyContent += `    play music ${generateScriptAssetName(asset, initialMusic || "audio_placeholder")} fadein 2.0\n`;
      }
    

    // กรองบล็อกเหตุการณ์ที่สังกัดอยู่ในบทนี้มาทำการแยกแกะและสร้างเป็นคำสั่ง
    const chapterBlocks = blocks ? blocks.filter((b) => b.chapter_id === chapter.id) : [];
    if (chapterBlocks.length === 0) {
      rpyContent += `    pass\n\n`;
      return;
    }

    chapterBlocks.forEach((block) => {
      const type = String(block.type).toLowerCase().trim();
      let props = {};
      try {
        props = typeof block.properties === "string" ? JSON.parse(block.properties) : block.properties || {};
      } catch (e) {
        props = {};
      }

      // ฟังก์ชันย่อยสำหรับช่วยแกะและคำนวณเอฟเฟกต์การเปลี่ยนผ่านภาพ (Transitions)
      const getTransitionStr = (isSpriteBlock = false) => {
        let effectRaw = props?.backgroundEffect || props?.spriteEffect || props?.effect || props?.bg_effect || props?.transition || props?.["เอฟเฟกต์พื้นหลัง"] || block?.effect;
        const speedRaw = props?.backgroundEffectSpeed || props?.spriteSpeed || props?.speed || props?.bg_speed || props?.transition_speed || props?.["ความเร็วเอฟเฟกต์"] || ""; 
        const cleanSpeedToken = String(speedRaw).toLowerCase().trim();

        if (cleanSpeedToken === "none") return " with None";

        if (!effectRaw && isSpriteBlock) {
          if (cleanSpeedToken === "normal" || cleanSpeedToken === "") return "";
          effectRaw = "dissolve";
        }

        const cleanEffect = String(effectRaw || "").toLowerCase().trim();
        if (!cleanEffect || cleanEffect === "none" || cleanEffect.includes("ไม่มี")) return "";

        if (cleanSpeedToken === "normal" || cleanSpeedToken === "") return ` with ${cleanEffect}`;
        
        let duration = RENPY_SPEED_MAP[cleanSpeedToken] !== undefined ? RENPY_SPEED_MAP[cleanSpeedToken] : 0.5;
        if (cleanEffect === "dissolve") return ` with Dissolve(${duration})`; 
        if (cleanEffect === "fade") {
          let halfDuration = duration / 2;
          return ` with Fade(${halfDuration}, 0.0, ${halfDuration})`;
        }
        return ` with ${cleanEffect}`;
      };

      // -------------------------------------------------------------
      //  จุดที่ 3: โซนแปลงบล็อกแยกตามโมดูลเหตุการณ์ (Parser Layer)
      // -------------------------------------------------------------
      
      //  เคสที่ 3.1: บล็อกคำพูดและบทสนทนา (Dialogue)
      if (type === "dialogue" || type === "character" || type === "text") {
  const selectedAssetId = props?.selected_asset_id || block?.selected_asset_id || block?.asset_id;
  if (selectedAssetId && !isInvalidValue(selectedAssetId)) {
    const asset = findAsset(selectedAssetId, assets);
    if (asset) {
      const rawExpression = props?.expression || block?.properties?.expression || asset?.expression_tag || asset?.expression;
      const cleanExpression = rawExpression && rawExpression.trim() ? slugify(rawExpression).replace(/-/g, "_") : "";
      let spriteCommandName = generateScriptAssetName(asset, selectedAssetId);

      // 1. จัดการต่อชื่อสีหน้า (Expression) เข้ากับชื่อสไปรต์
      // ต่อพ่วงชื่อสไปรต์และอารมณ์สีหน้า
      if (cleanExpression) {
        if (spriteCommandName.includes("expr_")) {
          const basePart = spriteCommandName.split("expr_")[0];
          spriteCommandName = `${basePart}${cleanExpression}`.trim();
        } else {
          spriteCommandName = `${spriteCommandName} ${cleanExpression}`;
        }
      }

      // 2.  เพิ่มการดึงค่าตำแหน่ง (spriteposition)
      // ดึงพิกัดตำแหน่งสไปรต์ (left, center, right) มาประกบเขียนลงไฟล์ เช่น `show a at left`
      const rawPosition = props?.spriteposition || block?.spriteposition || block?.properties?.spriteposition;
      const cleanPosition = rawPosition && rawPosition.trim() ? rawPosition.trim().toLowerCase() : "";
      
      // ถ้ามีตำแหน่งกำหนดไว้ ให้เจน string " at left" / " at center" / " at right"
      const positionSuffix = cleanPosition ? ` at ${cleanPosition}` : "";

      // 3. รวมร่างคำสั่งเขียนลงไฟล์ .rpy (ลดรูปไม่ต้องเขียน rpyContent += แยกไอเอฟ)
      rpyContent += `    show ${spriteCommandName}${positionSuffix}\n`;
    }
  }
  
  // โซนจัดการกล่องข้อความและชื่อคนพูดด้านล่าง (คงเดิม)
  // เขียนบรรทัดบทสนทนาและชื่อผู้พูดลงไปด่านล่างภาพตัวละคร
  const cleanContent = escapeDialog(block.content || props.text || props.dialogue || "");
  if (block.character_name) {
    const rawName = block.character_name.trim();
    const assignedVar = charMap[rawName];
    rpyContent += assignedVar ? `    ${assignedVar} "${cleanContent}"\n` : `    "${escapeDialog(rawName)}" "${cleanContent}"\n`;
  } else {
    rpyContent += `    "${cleanContent}"\n`; // กล่องคำพูดแบบไม่มีชื่อคนพูด (บรรยายลอยๆ)
  }
}
      //  เคสที่ 3.2: บล็อกภาพฉากหลัง (Background / Scene)
      else if (type === "background" || type === "bg" || type === "scene" || type === "ภาพพื้นหลัง") {
        let bgRaw = block.asset_id || props.bg_name || props.background || props.bg || props.scene || props?.["ฉากพื้นหลัง"] || block.content;
        const asset = findAsset(bgRaw, assets);
        const bgName = generateScriptAssetName(asset, isInvalidValue(bgRaw) ? "bedroom" : bgRaw);
        rpyContent += `    scene ${bgName}${getTransitionStr()}\n`;
      } 
      
      //  เคสที่ 3.3: บล็อกควบคุมสไปรต์ตัวละครเดี่ยว (Sprite Show / Hide Control)
      else if (type === "sprite" || type === "character_sprite" || type === "ตัวละคร" || type === "ภาพตัวละคร") {
        let spriteRaw = block.asset_id || props.sprite_name || props.sprite || props.character || props.selected_asset_id || props?.["ภาพตัวละคร (Sprite)"] || block.content;
        const asset = findAsset(spriteRaw, assets);
        let spriteCommandName = generateScriptAssetName(asset, isInvalidValue(spriteRaw) ? "character_placeholder" : spriteRaw);
        
        if (asset && asset.expression_tag && asset.expression_tag.trim()) {
          const cleanExpr = slugify(asset.expression_tag).replace(/-/g, "_");
          if (spriteCommandName.includes("expr_")) {
            const basePart = spriteCommandName.split("expr_")[0];
            spriteCommandName = `${basePart}${cleanExpr}`.trim();
          } else {
            spriteCommandName = `${spriteCommandName} ${cleanExpr}`;
          }
        }
        
        let hideTagName = spriteCommandName.includes(" ") ? spriteCommandName.split(" ")[0] : spriteCommandName;
        const actionRaw = props.spritecommand || props.action || props?.["คำสั่งภาพตัวละคร"] || "show";
        const action = String(actionRaw).toLowerCase().includes("hide") || String(actionRaw).includes("ซ่อน") ? "hide" : "show";
        const position = props.spriteposition || props.position || props?.["ตำแหน่งภาพตัวละคร"] || "center";

        if (action === "hide") {
          rpyContent += `    hide ${hideTagName}${getTransitionStr(true)}\n`;
        } else {
          rpyContent += `    show ${spriteCommandName} at ${position}${getTransitionStr(true)}\n`;
        }
      }
      
      // เคสที่ 3.4: บล็อกควบคุมระบบเสียง (Audio / Music / Sound SFX)
      else if (type === "audio" || type === "music" || type === "sound" || type === "เสียง") {
        const audioAction = String(props.audiocommand || props.command || "play").toLowerCase().trim();
        let audioRaw = block.asset_id || props.selected_asset_id || block.content || props.audio_name || props.music_name || props?.["เลือกไฟล์เสียง"];
        const asset = findAsset(audioRaw, assets);
        const audioName = generateScriptAssetName(asset, isInvalidValue(audioRaw) ? "audio_placeholder" : audioRaw);
        const audioTypeRaw = props.audiotype || props.audio_type || props?.["ประเภทเสียง"] || (asset ? asset.file_type : "");
        const isSoundEffect = String(audioTypeRaw).toLowerCase().includes("sound") || String(audioTypeRaw).toLowerCase().includes("sfx") || String(audioTypeRaw).includes("เอฟเฟกต์");
        
        if (audioAction === "stop") {
          rpyContent += `    stop ${isSoundEffect ? "sound" : "music"}\n`;
        } else {
          rpyContent += `    play ${isSoundEffect ? "sound" : "music"} ${audioName}\n`;
        }
      }
      //  เคสที่ 3.5: บล็อกสร้างทางเลือกเนื้อเรื่องแยกย่อย (Choice / Interactive Menu)
      else if (type === "choice" || type === "menu" || type === "options") {
        let options = props.choice || props.options || props.choices || block.options || [];
        rpyContent += `    menu:\n`;
        if (options.length === 0) {
          rpyContent += `        "ดำเนินเนื้อเรื่องต่อไป":\n            pass\n`;
        } else {
          // วนลูปวาดตัวเลือกแต่ละปุ่มพร้อมแผนผังตรรกะคำสั่งภายในตัวเลือกนั้นๆ
          options.forEach((opt) => {
            let optText = typeof opt === "string" ? opt : opt.text || opt.title || opt.label || "ทางเลือก";
            let targetChapterId = opt?.target_destination?.type === "NEW_CHAPTER" ? opt.target_destination.chapter_id : opt.target_chapter_id || opt.targetId;
            
            rpyContent += `        "${escapeDialog(optText)}":\n`;
            let hasAction = false;

            // หากมีบทพูดแทรกเฉพาะภายในทางเลือกนั้น (Dialogues List Inside Option) ให้เรนเดอร์ยัดลงไปตามย่อหน้า
            if (opt.dialoguesList) {
              opt.dialoguesList.forEach((d) => {
                const dText = typeof d === "object" ? d.text : d;
                const rawName = typeof d === "object" && d.character ? d.character.trim() : "";

                if (dText?.trim()) {
                  if (rawName) {
                    const assignedVar = charMap[rawName];
                    rpyContent += assignedVar 
                      ? `            ${assignedVar} "${escapeDialog(dText)}"\n` 
                      : `            "${escapeDialog(rawName)}" "${escapeDialog(dText)}"\n`;
                  } else {
                    rpyContent += `            "${escapeDialog(dText)}"\n`;
                  }
                  hasAction = true;
                }
              });
            }

            // คำสั่งกระโดดเส้นเรื่อง: หากคลิกข้อนี้ ให้ผูกสคริปต์ `jump` ข้ามไปยังบทเรียนเป้าหมาย
            if (targetChapterId) {
              const targetIndex = chapters.findIndex((c) => String(c.id) === String(targetChapterId));
              if (targetIndex !== -1) {
                const targetLabel = targetIndex === 0 ? "start" : chapters[targetIndex].label_name || `chapter_${String(targetChapterId).replace(/-/g, "_")}`;
                rpyContent += `            jump ${targetLabel}\n`;
                hasAction = true;
              }
            }
            if (!hasAction) rpyContent += `            pass\n`;
          });
        }
      }
      
      // เคสที่ 3.6: บล็อกกระโดดข้ามเส้นเรื่องทันทีแบบไร้เงื่อนไข (Unconditional Jump Block)
      else if (type === "jump") {
        const targetChapterId = block.target_chapter_id || props.target_chapter_id;
        const targetIndex = chapters.findIndex((c) => String(c.id) === String(targetChapterId));
        rpyContent += targetIndex !== -1 ? `    jump ${targetIndex === 0 ? "start" : chapters[targetIndex].label_name || `chapter_${String(targetChapterId).replace(/-/g, "_")}`}\n` : `    return\n`;
      }
    });
    rpyContent += `    \n`;
  });

  return rpyContent;
}

// ล้างคำภาษาไทยเป็นคาราโอเกะพิมพ์เล็ก ป้องกันโฟลเดอร์รันใน Windows/Mac ของผู้เล่นบางคนไม่ได้
export const convertToSlug = (name) => {
  // 1. แปลงภาษาไทย/ภาษาอื่น ให้เป็นภาษาอังกฤษคาราโอเกะก่อน
  const transliterated = slugify(name); 

  // 2. นำค่าคาราโอเกะที่ได้มาล้างคราบอักขระพิเศษตามกฎของ Ren'Py และยุบช่องว่างเป็น _
  const cleanSlug = transliterated
    .toLowerCase()
    .replace(/[^a-z0-9\s_-]/g, '') // ลบอักขระที่ Ren'Py ไม่รองรับ
    .trim()
    .replace(/\s+/g, '_')          // เปลี่ยนช่องว่างเป็น _
    .replace(/_+/g, '_');          // ป้องกัน _ ซ้ำซ้อน

  // 3. ป้องกันกรณีเคสหลุด เช่น ชื่อว่างเปล่า ให้คืนค่า Fallback เป็น project_timestamp
  return cleanSlug || `project_${Date.now()}`;
};

// -------------------------------------------------------------
// 📌 จุดที่ 4: ฟังก์ชัน `generateConfigString` (ตัวสร้างไฟล์กำหนดค่าระบบ)
// -------------------------------------------------------------
// สั่งสร้างข้อความในไฟล์ `project_config.rpy` เพื่อกำหนดชื่อโปรเจกต์ของเกม 
// ปรับค่า Transition ตัวเปลี่ยนฉากพื้นฐานของทั้งระบบให้เป็น dissolve ละมุนสายตาแบบปลอดภัย
export function generateConfigString(projectName) {
  const buildName = convertToSlug(projectName);
  
  return [
    `# ⚠️ Auto-generated configuration override by Scenario Management System`,
    `# This file safe-overrides the game name without wiping out your default options.rpy`,
    `init offset = 1`,
    ``,
    `define config.name = _("${escapeDialog(projectName)}")`,
    `define build.name = "${buildName}"`,
    ``,
    //`define config.main_menu_music_fadeout = 1.5`,
    `define config.say_attribute_transition = dissolve`,
    `define config.enter_transition = dissolve`,
    `define config.exit_transition = dissolve`,
  ].join('\n');
}

// -------------------------------------------------------------
// 📌 จุดที่ 5: ฟังก์ชัน `generateAssetsRpy` (ตัวสร้างทะเบียนคลังภาพ)
// -------------------------------------------------------------
// สแกนลิสต์ Asset ทั้งหมด เพื่อลงทะเบียนจับคู่ระหว่าง คีย์เวิร์ดเรียกใช้ภาพในโค้ด กับ ที่อยู่ของไฟล์ภาพจริงในเครื่อง
// 💥 จุดเด่น: มีการเขียนสคริปต์ผูกค่าอัตราการขยาย (zoom) และจุดขยับแกน Y ในแนวตั้ง (yoffset) 
// หน่วยพิกเซล ลงไปกำกับไว้ที่ตัวแปรภาพภาพตัวละคร เพื่อแก้ปัญหาภาพตัวละครลอย ล้น หรือเตี้ยเกินไปบนหน้าจอผู้เล่น
export function generateAssetsRpy(assetsList) {
  if (!assetsList || assetsList.length === 0) return "";

  let rpyContent = "# =========================================\n";
  rpyContent += "# AUTOMATICALLY GENERATED ASSETS DEFINITION\n";
  rpyContent += "# =========================================\n\n";

  assetsList.forEach((asset) => {
    if (!asset.file_name) return;

    const fileType = (asset.file_type || "").toLowerCase();
    const matchExt = asset.file_name ? asset.file_name.match(/\.[^.]+$/) : null;
    const ext = matchExt ? matchExt[0].toLowerCase() : "";

    // คัดกรองไฟล์เสียงออกไป: เพราะเอนจิน Ren'Py เรียกไฟล์เสียงตรงผ่านพาร์ธได้ทันที ไม่ต้องประกาศตัวแปรภาพล่วงหน้า
    const isAudio = fileType.includes("music") || 
                    fileType.includes("audio") || 
                    fileType.includes("sound") || 
                    fileType.includes("sfx") || 
                    fileType.includes("bgm") || 
                    fileType.includes("summit") || 
                    [".mp3", ".wav", ".ogg", ".opus"].includes(ext);

    if (isAudio) return; 

    const isSprite = fileType.includes("sprite");
    let finalFileName = generateZipFileName(asset, false);

    if (isSprite) {
      const rawExpression = asset.expression_tag;
      if (rawExpression && rawExpression.trim()) {
        let cleanExpr = slugify(rawExpression).replace(/-/g, "_");
        if (cleanExpr) {
          const dotIndex = finalFileName.lastIndexOf(".");
          if (dotIndex !== -1) {
            const baseName = finalFileName.substring(0, dotIndex);
            const fileExt = finalFileName.substring(dotIndex);
            finalFileName = `${baseName} ${cleanExpr}${fileExt}`;
          } else {
            finalFileName = `${finalFileName} ${cleanExpr}`;
          }
        }
      }
    }

    const lastDotIndex = finalFileName.lastIndexOf(".");
    const imageName = lastDotIndex !== -1 ? finalFileName.substring(0, lastDotIndex) : finalFileName;
    
    // เขียนโค้ดลงทะเบียนภาพลงสคริปต์
    /*rpyContent += `image ${imageName}:\n`;
    rpyContent += `    "images/${finalFileName}"\n`;*/

    // คีย์เวิร์ดเด็ด: เติมค่าคอนฟิกตำแหน่งทางเทคนิคลงไปคุมท้ายภาพตัวละคร
    if (isSprite) {
  // 🟢 โค้ดสำหรับภาพตัวละคร (ใช้ Block style)
  const zoom = asset.transform_config?.zoom ?? 1.0;
  const yoffset = asset.transform_config?.yoffset ?? 0;

  rpyContent += `image ${imageName}:\n`;
  rpyContent += `    "images/${finalFileName}"\n`;
  rpyContent += `    zoom ${Number(zoom).toFixed(2)}\n`;
  rpyContent += `    yoffset ${parseInt(yoffset)}\n\n`;
    } else {
      rpyContent += `image ${imageName} = Transform("images/${finalFileName}", size=(1920, 1080), fit="cover")\n\n`;
    }
  });

  return rpyContent;
}